# Generated by Django 2.2.7 on 2019-11-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_source', models.CharField(max_length=200)),
                ('compaign_name', models.CharField(max_length=200)),
                ('clicks', models.DecimalField(blank=True, decimal_places=0, max_digits=10)),
                ('impressions', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
            ],
        ),
    ]
